server:
  port: 8082

spring:
  application:
    name: catalog-service
  profiles:
    active: sqlite
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: catalog-group
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    org.hibernate.SQL: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

app:
  security:
    admin:
      username: admin
      password: password
