spring:
  application:
    name: educatalog
  datasource:
    url: jdbc:sqlite:educatalog.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
