server:
  port: 8083

spring:
  application:
    name: progress-service
  profiles:
    active: sqlite
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: progress-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

logging:
  level:
    org.hibernate.SQL: INFO
